### ISSUE TITLE
Update Datathon Events

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#142]
This issue will: 

- [x] Update NY datathon event page - submissions are closed, and direct to open call for Montreal datathon 
- [x] re-structures sponsor list
- [x] Update event page to better reflect past events (added host column), and adds in new header - Upcoming datathons/workshops to highlight Montreal datathon and outbound link; also highlights NY upcoming event.

**Comment by ianmilligan1** [comment]
Closed with fc2de7a00658caca7574b9c16caffb8023e4b1ff
