### ISSUE TITLE
404 for Washington event page

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#168]
investigate and resolve why https://archivesunleashed.org/washington is throwing a 404 error

**Comment by ianmilligan1** [comment]
Oh, @ruebot and I ran into some problems with the site yesterday. I can fix it. Are there any other pages that you know that are throwing 404s?

**Comment by SamFritz** [comment]
Addressed issue surrounding upper-case “Washington” and a lower-case “washington” in URL. 

Fix implemented by @ianmilligan1
