### ISSUE TITLE
General Updates

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#178]
Updating website with following changes

Getting Started Page - The Cloud
- Update screen shots 

Archives Unleashed Cloud
- Update screen shots
- Update prose a bit to reflect recent work (new graphs)

Get Involved
- Upload recent newsletter

Publication Page
- Have section at top for AU materials (datathon, community report, etc.)
- Add in DL journal article

**Comment by ianmilligan1** [comment]
Closed with 22e88f2ae0bb45216512fdccd155b16375a37abe
