### ISSUE TITLE
Include citation information

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#185]
A follow up to [AUT issue 497](https://github.com/archivesunleashed/aut/issues/497), implementing citation information on the project website with the following phrase:

**Citing Archives Unleashed**

How to cite the Archives Unleashed Toolkit or Cloud in your research:

Nick Ruest, Jimmy Lin, Ian Milligan, and Samantha Fritz. 2020. The Archives Unleashed Project: Technology, Process, and Community to Improve Scholarly Access to Web Archives. In Proceedings of the ACM/IEEE Joint Conference on Digital Libraries in 2020 (JCDL '20). Association for Computing Machinery, New York, NY, USA, 157–166. DOI:https://doi.org/10.1145/3383583.3398513

Your citations help to further the recognition of using open-source tools for scientific inquiry, assists in growing the web archiving community, and acknowledges the efforts of contributors to this project.

This information will be listed as a new header under the "About the Project" section.

**Comment by ianmilligan1** [comment]
Closed with 1c8482b
