### ISSUE TITLE
AU Cohort Page/Menu Template

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#194]
First ticket to address adding in AU Cohort #1 material to project website. 

- [x] Cohorts page will be new page (not to be included under events)
- [x] Add in banner/button/link on home page to draw attention to Cohorts

Deploy Cohort pages once we open applications (Mid-Feb)

Page Content to include:
- [x] Information about the event
- [x] link to download PDF for application
- [x] important dates
- [x] organizers
- [x] schedule

**Comment by ianmilligan1** [comment]
Added in a stub page at `content/cohorts` (I went with plural)

Right now I have it here in the menu:

![Screen Shot 2021-01-27 at 9 55 57 PM](https://user-images.githubusercontent.com/3834704/106083402-71a22e80-60ea-11eb-9809-217226b4fb08.png)

If you want to change the relative position, we can tweak the `weight` value in `config.toml`. 👍

**Comment by SamFritz** [comment]
Addressed with [PR: 196](https://github.com/archivesunleashed/archivesunleashed.org/pull/196), merged and published
