### ISSUE TITLE
General Updates for Cohorts (ongoing)

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#217]
opening a ticket to address updating cohort page with information, links, etc that teams will be providing over next year. 

- [x] Add in project site for Team Rubric - Niagara Crisis Communication --> https://brockdsl.github.io/archives_unleashed/posts/introduction_to_the_project/

Will also keep open branch [issue-217] for these tasks

**Comment by ianmilligan1** [comment]
Ribaric website added in 98ca8f3ecef598f4fc680f08ae0f37457bcfcb04. 👍

**Comment by SamFritz** [comment]
- [ ] Add in C2 projects

**Comment by SamFritz** [comment]
There are no foreseeable changes to cohort pages, closing issue
