### ISSUE TITLE
Toronto Datathon Final Projects

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#43]
Create a section on the Toronto datathon page to display team participants, bios (if provided), and link to presentation slides. Need to insert a clickable image that links to a PDF of slide deck. This will be used to promote the collaboration coming out of the event and to highlight examples of projects for future datathon participants. 

Wireframing has already been started locally

**Comment by SamFritz** [comment]
Challenges wit using markdown to format table detailing project participants and presentation. Used simple html table with no additional formatting. 

Table includes:
- participant names and institution
- one image from group's slide deck
- presentation - link to open PDF in new window.

commit: 8854ed9ae4d3040e20dae0ceaf3c7c58b5895a7a

**Comment by SamFritz** [comment]
Since the event is over, I think it would be best to hide travel information with a <----!> that way we can display and promote projects. @ianmilligan1 @ruebot this okay with you?

**Comment by ianmilligan1** [comment]
Totally agree - or you can even just delete it, there'll be the copy kept in the GitHub version history (and we have it roughed out over on the Vancouver page).

**Comment by ianmilligan1** [comment]
Closed with #45 - looks great! 🎉
