### ISSUE TITLE
Vancouver Schedule

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#59]
Update Vancouver datathon page to include the schedule. 

Will mimic format from Toronto page: 
- hyperlink to open as PDF document
- image of the schedule to be displayed in a table format (day 1 in column 1, day 2 in column 2) and clickable to open as PDF

**Comment by ianmilligan1** [comment]
Closed with fe8284c4ffaf98226fe2a2edf6a4598e3294367d.
