### ISSUE TITLE
Document DataFrames

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/archivesunleashed.org#61]
We need to document DataFrames in the documentation. Discussed with @ruebot and I think we will document DF alongside RDDs in the existing docs.

I will draw from:
- [Initial discussions here](https://github.com/archivesunleashed/aut/issues/190)
- [Images Links](https://github.com/archivesunleashed/aut/pull/221)
- [Image Details](https://github.com/archivesunleashed/aut/pull/226)
- [Image Save](https://github.com/archivesunleashed/aut/pull/234)

**Comment by lintool** [comment]
We can draw inspiration from the Spark docs:
https://spark.apache.org/docs/latest/rdd-programming-guide.html

You see how for each task, it tells you how to do in Scala, Java, and Python - each in its tab. Perhaps we can organize that way also?

For now, if we can't do it in DF, we just say so.
