### ISSUE TITLE
Create Datathon Cheat Sheet

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/archivesunleashed.org#68]
Based on some feedback. 

For the next datathon, let's create a cheat sheet of common things. In the past, we've had this in Slack but would be better placed in the website too.

some example topics:
- [x] how to find your terminal;
- [x] how to `ssh` into the server, `chmod`, etc.
- [x] how to launch AUT;
- [x] standard dataset techniques & examples;
- [x] how to copy files to/from a virtual machine.

**Comment by greebie** [comment]
A few others to consider:
[ ] access ssh via Putty
[ ] common Spark commands (eg. map, filter, fold etc.)
[ ] a quick explanation of the spark launching commands master(local[*]) etc.

**Comment by ianmilligan1** [comment]
Decided to tackle this today. I'll stage as a PR for review.

I don't know how to use Putty nor am I going to figure it out without a Windows box (I need to get one at some point, tbh).I don't think common Spark commands belong on this cheat sheet – I put some in from your earlier reference guide and felt it got a bit too technical for the audience we're aiming this particular page at. That said, maybe we could revive your reference guide as a separate page at some point @greebie.
