### ISSUE TITLE
Update Vancouver Page Projects

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#70]
Updating Vancouver datathon page to include information about final projects. 
- [x] Team name
- [x] Team members + affiliation
- [x] Screenshot of project
- [x] Attached project presentation (pdf)

**Comment by ianmilligan1** [comment]
Resolved with 31a3b3c5a963d040c10ea69b21448a017d23d320, thanks @SamFritz!
