### ISSUE TITLE
Archives Unleashed Newsletters - PDF access

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#75]
Upload newsletters to the website via the get involved page. 
Create a new header specifically for past issues of newsletters. 

Right now, only those who are subscribers get the newsletter, this will allow us to share newsletters after the campaigns have been sent out, and for individuals to access them at any time.

**Comment by ianmilligan1** [comment]
Closed with 814fc3be5c32e8f44de6201ed872ac95c20aa455
