### ISSUE TITLE
Update Washington Travel Information

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#80]
Update the Washington datathon page to include travel information for participants, info including:

Using branch: gw-travel

- [x] accommodation
- [x] airport
- [x] transportation options to airports
- [x] local transportation options
- [x] local attractions

PR and deployment will be issued right before participants are notified (Dec. 19).

**Comment by SamFritz** [comment]
@ianmilligan1 first draft of travel content is available. 

Feel free to have a look at your convenience and note anything I've overlooked/missed.

**Comment by ianmilligan1** [comment]
Closed with bad265214eb36fb31495c561ab582de55cc83479
