### ISSUE TITLE
Add Privacy Policy

### ISSUE THREAD

**Issue by SamFritz** [archivesunleashed/archivesunleashed.org#82]
Privacy policy was written to cover all archives unleashed domains. The policy will be added to the archivesunleashed.org website under the About page. 

Reorder of About menu to look like: 
- Project Team
- Advisory Board
- Funding
- Code of Conduct
- Privacy Policy

**Comment by ianmilligan1** [comment]
Closed with 5cd711f18490ed8ab2460109d659d88e874a8b8e
