### ISSUE TITLE
Update Docker lesson plan with new graph write commands

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/archivesunleashed.org#92]
Thanks for catching this @samfritz!

**Comment by SamFritz** [comment]
I think I was experiencing wifi interference yesterday when testing. 

This script runs successfuly

**Comment by SamFritz** [comment]
@ianmilligan1 Closing issue as script does not need updating.

**Comment by ianmilligan1** [comment]
Great, thanks!
